## Capstone Core Requirements

Proper Use of Version Control
- Your GitHub repository must include at least 10 separate commits
- It's best practice to commit every time you complete a work session to avoid data loss
- All commits must be made using the command line
- Do not use the file uploader, as this will result in project failure
Data Sources
- Your project must include at least two different datasets that can be combined meaningfully.
- The combined dataset should have a minimum of 1,000 rows and 10 columns.
- All sources must be cited and credited.
- Data Analysis
- Use Python (Pandas) for data cleaning, wrangling, and exploratory data analysis (EDA).
- Demonstrate handling of missing data, duplicates, data types, and transformations.
Database & SQL
- Design a relational database and explain your reasoning.
- Create and include an Entity-Relationship Diagram (ERD).
- Build the database in SQLite3 using Python.
- Include at least three intermediate/advanced SQL queries (joins, grouping/aggregation, having, subqueries, etc.).
Functions & Automation
- Write at least three unique, custom Python functions that serve a clear purpose or automate repetitive tasks.
Visualizations
- Include at least three different chart types in your notebook.
- Visuals must be well-designed, labeled, and help tell a clear story.
Notebook Quality
- Use Markdown cells throughout your Jupyter Notebook to explain your reasoning, analysis, and conclusions.
- Properly use markdown language to format these cells.
- Code should include useful comments.
- Notebooks should be well-organized, professional, and free of typos or sloppy formatting. Repetitive or unnecessary code should be deleted.
Repository & README
- Your GitHub repository must include:
- A polished README.md (professional tone, no errors).
- A requirements.txt file.
- All data files (or scripts to reproduce them).
- Relative paths for all files so the project works across operating systems.
The README must contain:
- A unique project title (not including words: “capstone” or “Code:You”).
- Instructions for setting up, activating/deactivating a virtual environment, and running the project on all operating systems.
- Links to all data sources online with credit given and authors cited when possible.
- A summary of your main questions and findings (observations and conclusions)
- Acknowledgement of any tools, frameworks, or external assistance used - including libraries, frameworks, or AI tools (such as ChatGPT for code generation or editing support).

In [829]:
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np 
import seaborn as sns
import sqlite3

## The folowing is for TESTING the code multiple times
# The first deletes the dataframes so the load can be executed again
# The second deleted the SQL Lite tables in the database so they can be created again

In [ ]:
# FOR TESTING PURPOSES ONLY !!!!!!
# this will delete the dataframes so you can run the program multiple times
del df, df2, df3

In [ ]:
# For Testing Purposes Only !!!!!
# Drop tables for Testing Multiple times
cursor.execute("DROP TABLE IF EXISTS Animal;")
cursor.execute("DROP TABLE IF EXISTS Shelter;")
cursor.execute("DROP TABLE IF EXISTS Intake;")
cursor.execute("DROP TABLE IF EXISTS Outcome;")
cursor.execute("DROP TABLE IF EXISTS Species;")
conn.commit()

# Functions

In [830]:
# This function converts date fields to a datetime in order to do calculations
# Must be run after columns are renamed

def convert_date_columns(df, intake_col="intakeDate", outcome_col="outcomeDate"):
    df["indate"] = pd.to_datetime(df[intake_col], errors="coerce")
    df["outdate"] = pd.to_datetime(df[outcome_col], errors="coerce")
    return df

In [831]:
# This function calculates the length of stay in the shelter for each intake
# Must be run after columns are renamed and the convert_date_columns function

def add_length_of_stay(df):
    df["indate"] = pd.to_datetime(df["indate"], errors="coerce")
    df["outdate"] = pd.to_datetime(df["outdate"], errors="coerce")
    df["lengthOfStay"] = (df["outdate"] - df["indate"]).dt.days
    return df

In [832]:
# This function trims the dataframes to the time period of 01-01-2017 thru 07-31-2025
# Must be run after columns are renamed and the convert_date_columns function

def filter_by_date_range(df, start_date="2017-01-01", end_date="2025-07-31"):
    df["indate"] = pd.to_datetime(df["indate"], errors='coerce')
    df["outdate"] = pd.to_datetime(df["outdate"], errors='coerce')
    return df[
        (df["indate"] >= start_date) & (df["indate"] <= end_date) &
        (df["outdate"] >= start_date) & (df["outdate"] <= end_date)
    ]

# Load dataset from Louisville, KY

In [833]:
# Read in the csv file
# original csv file name was shortened for easier use

data = pd.read_csv('../data/kentucky_shelter_data.csv')

# Make a copy of the data to work with
df = data.copy()

# Preview and Analyze the data structure

In [834]:
df.head()

,kennel,animalid,jurisdiction,intype,insubtype,indate,surreason,outtype,outsubtype,outdate,animaltype,sex,bites,petsize,color,breed,sourcezipcode,ObjectId
0,408,A688221,40216,STRAY,OTC,2021-01-17 00:00:00,STRAY,TRANSPORT,RESCUE GRP,2021-02-06 00:00:00,DOG,M,N,PUPPY,BR BRINDLE,CHIHUAHUA SH / MIX,40218,1
1,ID07,A688234,40222,STRAY,OTC,2021-01-18 00:00:00,STRAY,RTO,IN FIELD,2021-01-18 00:00:00,DOG,N,N,MED,BR BRINDLE / WHITE,BOSTON TERRIER / MIX,40205,2
2,DW13,A688337,40118,STRAY,OTC,2021-01-21 00:00:00,STRAY,RTO,IN KENNEL,2021-01-23 00:00:00,DOG,S,N,LARGE,WHITE / BROWN,CATAHOULA / MIX,40118,3
3,INTAKE,A688419,40204,STRAY,OTC,2021-02-03 00:00:00,STRAY,TNR,CARETAKER,2021-02-04 00:00:00,CAT,S,N,MED,BLK TABBY,DOMESTIC SH,40204,4
4,INTAKE,A688478,40214,STRAY,OTC,2021-02-10 00:00:00,STRAY,TNR,CARETAKER,2021-02-11 00:00:00,CAT,N,N,MED,TORTIE,DOMESTIC SH,40210,5

In [835]:
df.tail()

,kennel,animalid,jurisdiction,intype,insubtype,indate,surreason,outtype,outsubtype,outdate,animaltype,sex,bites,petsize,color,breed,sourcezipcode,ObjectId
60338,N03,A743176,40272,STRAY,FIELD,2023-08-11 00:00:00,STRAY,ADOPTION,WALK IN,2023-10-03 00:00:00,DOG,S,N,LARGE,BLACK / BROWN,ROTTWEILER,40272,60339
60339,N31,A743450,40272,STRAY,OTC,2023-08-15 00:00:00,STRAY,ADOPTION,INTERNET,2023-09-18 00:00:00,DOG,N,N,MED,TAN / WHITE,PIT BULL,40272,60340
60340,FOUND,A743593,NaN,FOUND,WEB,2023-08-18 00:00:00,NaN,NaN,NaN,NaN,DOG,F,NaN,MED,BROWN,STAFFORDSHIRE,NaN,60341
60341,808,A743612,40215,STRAY,OTC,2023-08-19 00:00:00,STRAY,RTO,NaN,2023-08-29 00:00:00,DOG,M,N,MED,BR BRINDLE,CANE CORSO,40215,60342
60342,207,A743612,40215,STRAY,OTC,2024-06-28 00:00:00,STRAY,EUTH,BEHAV OBSV,2024-07-03 00:00:00,DOG,M,N,MED,BR BRINDLE,CANE CORSO,40215,60343

In [836]:
df.describe()

           ObjectId
count  60343.000000
mean   30172.000000
std    17419.667984
min        1.000000
25%    15086.500000
50%    30172.000000
75%    45257.500000
max    60343.000000

In [837]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60343 entries, 0 to 60342
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   kennel         60343 non-null  object
 1   animalid       60343 non-null  object
 2   jurisdiction   47038 non-null  object
 3   intype         60343 non-null  object
 4   insubtype      60216 non-null  object
 5   indate         60343 non-null  object
 6   surreason      47038 non-null  object
 7   outtype        46755 non-null  object
 8   outsubtype     37967 non-null  object
 9   outdate        46789 non-null  object
 10  animaltype     60343 non-null  object
 11  sex            59318 non-null  object
 12  bites          47053 non-null  object
 13  petsize        57919 non-null  object
 14  color          60342 non-null  object
 15  breed          60267 non-null  object
 16  sourcezipcode  50868 non-null  object
 17  ObjectId       60343 non-null  int64
dtypes: int64(1), object(17)
memory usage: 8.3+ MB

In [838]:
df.columns

Index(['kennel', 'animalid', 'jurisdiction', 'intype', 'insubtype', 'indate',
       'surreason', 'outtype', 'outsubtype', 'outdate', 'animaltype', 'sex',
       'bites', 'petsize', 'color', 'breed', 'sourcezipcode', 'ObjectId'],
      dtype='object')

In [839]:
df.shape

(60343, 18)

In [840]:
df.dtypes

kennel           object
animalid         object
jurisdiction     object
intype           object
insubtype        object
indate           object
surreason        object
outtype          object
outsubtype       object
outdate          object
animaltype       object
sex              object
bites            object
petsize          object
color            object
breed            object
sourcezipcode    object
ObjectId          int64
dtype: object

## Data Clean Up
- Rename Columns
- Add Shelter information
- Call Function to convert date columns to datetime format
- Call Function to trim data set to specific date range
- Drop columns not needed for analysis
- Check for Missing Data
- Count of Missing Data
- Replace necessary missing data
- Check for duplicates
- Drop Duplicate Columns
- Drop Duplicate Rows
- Call Function for Length of Stay

In [841]:
# Rename columns to clearer names for use
df.columns = ["kennelId",
"animalId",
"jurisdiction",
"intakeReason",
"intakeSubtype",
"intakeDate",
"surreason",
"outcome",
"outcomeSubtype",
"outcomeDate",
"species",
"sex",
"bites",
"petsize",
"color",
"breed",
"zipcode",
"objectId"
]

In [842]:
# Add Shelter Name, Location and Shelter ID Column

df['shelterName'] = 'Louisville Metro Animal Services'
df['shelterID'] = 'KYLMAS01'
df['city'] = 'Louisville'
df['state'] = 'KY'

In [843]:
# Verify column names

df.columns

Index(['kennelId', 'animalId', 'jurisdiction', 'intakeReason', 'intakeSubtype',
       'intakeDate', 'surreason', 'outcome', 'outcomeSubtype', 'outcomeDate',
       'species', 'sex', 'bites', 'petsize', 'color', 'breed', 'zipcode',
       'objectId', 'shelterName', 'shelterID', 'city', 'state'],
      dtype='object')

In [844]:
# Convert date columns to datetime so we can do date calculations
#df['indate'] = pd.to_datetime(df['intakeDate'], errors='coerce')
#df['outdate'] = pd.to_datetime(df['outcomeDate'], errors='coerce')

# Call the function to convert date columns to datetime to do calculations
df = convert_date_columns(df)

print(df.indate, df.outdate)

0       2021-01-17
1       2021-01-18
2       2021-01-21
3       2021-02-03
4       2021-02-10
           ...
60338   2023-08-11
60339   2023-08-15
60340   2023-08-18
60341   2023-08-19
60342   2024-06-28
Name: indate, Length: 60343, dtype: datetime64[ns] 0       2021-02-06
1       2021-01-18
2       2021-01-23
3       2021-02-04
4       2021-02-11
           ...
60338   2023-10-03
60339   2023-09-18
60340          NaT
60341   2023-08-29
60342   2024-07-03
Name: outdate, Length: 60343, dtype: datetime64[ns]

In [845]:
# This calls the function that trims the dataframes to the time period of 01-01-2017 thru 07-31-2025

df = filter_by_date_range(df)

In [846]:
# Drop columns not needed for analysis
df = df.drop(columns=["kennelId", "jurisdiction", "intakeSubtype", "surreason", "outcomeSubtype", "bites", "petsize", "zipcode", "objectId"])

In [847]:
# validate columns were droppped
df.columns

Index(['animalId', 'intakeReason', 'intakeDate', 'outcome', 'outcomeDate',
       'species', 'sex', 'color', 'breed', 'shelterName', 'shelterID', 'city',
       'state', 'indate', 'outdate'],
      dtype='object')

In [848]:
# check for missing data
df.isna()

,animalId,intakeReason,intakeDate,outcome,outcomeDate,species,sex,color,breed,shelterName,shelterID,city,state,indate,outdate
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60337,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
60338,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
60339,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
60341,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
60342,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [849]:
# count of missing data
df.isna().sum()

animalId         0
intakeReason     0
intakeDate       0
outcome         40
outcomeDate      0
species          0
sex              0
color            1
breed            1
shelterName      0
shelterID        0
city             0
state            0
indate           0
outdate          0
dtype: int64

In [850]:
# Fill missing data with simple placeholder text
# This avoids potential issues due to blanks
df['color'] = df['color'].fillna("unspecified")
df['breed'] = df['breed'].fillna("unknown")
df['species'] = df['species'].fillna('unspecified')
df['outcome'] = df['outcome'].fillna('unknown')

In [851]:
# count of missing data after filling in some columns
# missing data in outdate and outcome indicates animal remains in shelter
df.isna().sum()

animalId        0
intakeReason    0
intakeDate      0
outcome         0
outcomeDate     0
species         0
sex             0
color           0
breed           0
shelterName     0
shelterID       0
city            0
state           0
indate          0
outdate         0
dtype: int64

In [852]:
# check for duplicates
df.duplicated(keep = False)

0        False
1        False
2        False
3        False
4        False
         ...
60337    False
60338    False
60339    False
60341    False
60342    False
Length: 46740, dtype: bool

In [853]:
# count of duplicated data
df.duplicated(keep = False).sum()

np.int64(44)

In [854]:
# drop duplicate rows
df = df.drop_duplicates(keep="first")

In [855]:
# This calls the function that calculates the length of stay and adds it to the dataframe

df = add_length_of_stay(df)

In [856]:
# verify final columns

df.columns

Index(['animalId', 'intakeReason', 'intakeDate', 'outcome', 'outcomeDate',
       'species', 'sex', 'color', 'breed', 'shelterName', 'shelterID', 'city',
       'state', 'indate', 'outdate', 'lengthOfStay'],
      dtype='object')

In [857]:
# Count number of animals by type and outcome
outcome_table = df.pivot_table(index='species', columns='outcome', aggfunc='size', fill_value=0)

print(outcome_table)

outcome     ADOPTION  DIED  DISPOSAL  EUTH  FOSTER  FOUND EXP  LOST  RELEASE  \
species
BIRD              60     5         9     6      11          0     1        0
CAT             5412   355       231  1132    4144          0     8       12
DOG             8268    68       379  1707    4518          3    31        3
GUINEA PIG         2     0         0     1      10          0     0        0
LIVESTOCK          2     0         7     0       1          0     0        0
OTHER             32     5        59   130      31          0     1        1
RABBIT            12     4         3     3     101          0     0        0

outcome     RTF   RTO   SNR   TNR  TRANSFER  TRANSPORT  unknown
species
BIRD          0     4     0     0        25          0        5
CAT         917   477  5645  3178      1429          4       12
DOG           0  5182     0     1      2464        294       22
GUINEA PIG    0     1     0     0        12          0        0
LIVESTOCK     0    15     0     0        16          0        0
OTHER         0     9     0     0        14          2        1
RABBIT        0     5     0     0       216          0        0

# Load dataset from Bloomington, IN

In [858]:
# Read in the csv file
data2 = pd.read_csv('../data/BloomingtonIN_Animal_Shelter_Animals.csv')

# Make a copy of the data to work with
df2 = data2.copy()

# Preview and Analyze the data structure

In [859]:
df2.head()

,id,intakedate,intakereason,istransfer,sheltercode,identichipnumber,animalname,breedname,basecolour,speciesname,...,movementdate,movementtype,istrial,returndate,returnedreason,deceaseddate,deceasedreason,diedoffshelter,puttosleep,isdoa
0,15801,11/28/2009 12:00:00 AM,Moving,False,C09115463,0A115D7358,Jadzia,Domestic Short Hair,Tortoiseshell,Cat,...,05/13/2017 12:00:00 AM,Adoption,False,10/31/2024 12:00:00 AM,Owner requested Euthanasia,10/31/2024 12:00:00 AM,Owner Requested,False,True,False
1,15932,12/08/2009 12:00:00 AM,Moving,False,D09125594,0A11675477,Gonzo,German Shepherd Dog/Mix,Tan,Dog,...,04/24/2017 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False
2,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,04/15/2017 12:00:00 AM,Adoption,False,02/28/2020 12:00:00 AM,Stray,06/28/2024 12:00:00 AM,Court Order/ Legal,True,False,False
3,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,02/29/2020 12:00:00 AM,Reclaimed,False,11/06/2023 12:00:00 AM,Stray,06/28/2024 12:00:00 AM,Court Order/ Legal,True,False,False
4,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,12/17/2023 12:00:00 AM,Adoption,False,NaN,Stray,06/28/2024 12:00:00 AM,Court Order/ Legal,True,False,False

In [860]:
df2.tail()

,id,intakedate,intakereason,istransfer,sheltercode,identichipnumber,animalname,breedname,basecolour,speciesname,...,movementdate,movementtype,istrial,returndate,returnedreason,deceaseddate,deceasedreason,diedoffshelter,puttosleep,isdoa
41382,84919,09/18/2025 11:31:53 AM,Stray,False,C25091320,NaN,Cobweb,Domestic Short Hair,Seal Point,Cat,...,09/18/2025 12:00:00 AM,Foster,False,NaN,Stray,09/18/2025 12:00:00 AM,Died in care,False,False,False
41383,84928,09/19/2025 11:13:42 AM,Housing,False,C25091819,981020059869571,Roo,Domestic Short Hair,Grey and White,Cat,...,09/25/2025 12:00:00 AM,Retailer,False,NaN,Stray,NaN,Court Order/ Legal,False,False,False
41384,84935,09/19/2025 03:38:02 PM,Stray,False,D25091323,981020000260872,Pikachu,Shih Tzu/Yorkshire Terrier,Tan and Brown,Dog,...,09/20/2025 12:00:00 AM,Reclaimed,False,NaN,Stray,NaN,Court Order/ Legal,False,False,False
41385,84937,09/19/2025 04:33:01 PM,Housing,False,C25091318,981020061749064,Blizzard,Siamese,Lynx point,Cat,...,09/20/2025 12:00:00 AM,Adoption,True,NaN,Stray,NaN,Court Order/ Legal,False,False,False
41386,84947,09/22/2025 12:18:36 PM,Housing,False,D25091322,982126059431489,Indy,Beagle,Tricolour,Dog,...,09/23/2025 12:00:00 AM,Reclaimed,False,09/23/2025 12:00:00 AM,Housing,NaN,Court Order/ Legal,False,False,False

In [861]:
df2.describe()

                 id
count  41387.000000
mean   70878.188175
std     8354.369853
min    15801.000000
25%    63908.000000
50%    72336.000000
75%    77794.000000
max    84947.000000

In [862]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41387 entries, 0 to 41386
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                41387 non-null  int64
 1   intakedate        41387 non-null  object
 2   intakereason      41385 non-null  object
 3   istransfer        41387 non-null  bool
 4   sheltercode       41387 non-null  object
 5   identichipnumber  36768 non-null  object
 6   animalname        41387 non-null  object
 7   breedname         41310 non-null  object
 8   basecolour        41387 non-null  object
 9   speciesname       41387 non-null  object
 10  animalage         41387 non-null  object
 11  sexname           41387 non-null  object
 12  location          41387 non-null  object
 13  movementdate      34799 non-null  object
 14  movementtype      34799 non-null  object
 15  istrial           41387 non-null  bool
 16  returndate        13258 non-null  object
 17  returnedreason    41387 non-null  object
 18  deceaseddate      1441 non-null   object
 19  deceasedreason    41387 non-null  object
 20  diedoffshelter    41387 non-null  bool
 21  puttosleep        41387 non-null  bool
 22  isdoa             41387 non-null  bool
dtypes: bool(5), int64(1), object(17)
memory usage: 5.9+ MB

In [863]:
df2.columns

Index(['id', 'intakedate', 'intakereason', 'istransfer', 'sheltercode',
       'identichipnumber', 'animalname', 'breedname', 'basecolour',
       'speciesname', 'animalage', 'sexname', 'location', 'movementdate',
       'movementtype', 'istrial', 'returndate', 'returnedreason',
       'deceaseddate', 'deceasedreason', 'diedoffshelter', 'puttosleep',
       'isdoa'],
      dtype='object')

In [864]:
df2.shape

(41387, 23)

In [865]:
df2.dtypes

id                   int64
intakedate          object
intakereason        object
istransfer            bool
sheltercode         object
identichipnumber    object
animalname          object
breedname           object
basecolour          object
speciesname         object
animalage           object
sexname             object
location            object
movementdate        object
movementtype        object
istrial               bool
returndate          object
returnedreason      object
deceaseddate        object
deceasedreason      object
diedoffshelter        bool
puttosleep            bool
isdoa                 bool
dtype: object

## Data Clean Up
- Rename Columns
- Add Shelter information
- Call Function to convert date columns to datetime format
- Call Function to trim data set to specific date range
- Drop columns not needed for analysis
- Check for Missing Data
- Count of Missing Data
- Replace necessary missing data
- Check for duplicates
- Drop Duplicate Columns
- Drop Duplicate Rows
- Call Function for Length of Stay

In [866]:
# Rename columns to clearer names for use
df2.columns = ["animalId", 
"intakeDate",
"intakeReason", 
"istransfer",
"shelter",
"chip",
"name",
"breed",
"color",
"species",
"age",
"sex",
"location",
"outcomeDate",
"outcome",
"istrial",
"returndate",
"returnedreason",
"deceaseddate",
"deceasedreason",
"diedoffshelter",
"putToSleep",
"isdoa"]

In [867]:
# Add Shelter Name, Location and Shelter ID Column

df2['shelterName'] = 'Bloomington Animal Services'
df2['shelterID'] = 'INBLAS01'
df2['city'] = 'Bloomington'
df2['state'] = 'IN'

In [868]:
# Verify name change

df2.columns

Index(['animalId', 'intakeDate', 'intakeReason', 'istransfer', 'shelter',
       'chip', 'name', 'breed', 'color', 'species', 'age', 'sex', 'location',
       'outcomeDate', 'outcome', 'istrial', 'returndate', 'returnedreason',
       'deceaseddate', 'deceasedreason', 'diedoffshelter', 'putToSleep',
       'isdoa', 'shelterName', 'shelterID', 'city', 'state'],
      dtype='object')

In [869]:
# Convert date columns to datetime so we can do date calculations
#df2['indate'] = pd.to_datetime(df2['intakeDate'], errors='coerce')
#df2['outdate'] = pd.to_datetime(df2['outcomeDate'], errors='coerce')

# Call the function to convert date columns to datetime to do calculations

df2 = convert_date_columns(df2)

print(df2.indate, df2.outdate)

/var/folders/6j/ng0s8_v10mj7kwbwccbbwd840000gn/T/ipykernel_32688/2655616905.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["indate"] = pd.to_datetime(df[intake_col], errors="coerce")

0       2009-11-28 00:00:00
1       2009-12-08 00:00:00
2       2012-08-10 00:00:00
3       2012-08-10 00:00:00
4       2012-08-10 00:00:00
                ...
41382   2025-09-18 11:31:53
41383   2025-09-19 11:13:42
41384   2025-09-19 15:38:02
41385   2025-09-19 16:33:01
41386   2025-09-22 12:18:36
Name: indate, Length: 41387, dtype: datetime64[ns] 0       2017-05-13
1       2017-04-24
2       2017-04-15
3       2020-02-29
4       2023-12-17
           ...
41382   2025-09-18
41383   2025-09-25
41384   2025-09-20
41385   2025-09-20
41386   2025-09-23
Name: outdate, Length: 41387, dtype: datetime64[ns]

/var/folders/6j/ng0s8_v10mj7kwbwccbbwd840000gn/T/ipykernel_32688/2655616905.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["outdate"] = pd.to_datetime(df[outcome_col], errors="coerce")

In [870]:
# This calls the function that trims the dataframes to the time period of 01-01-2017 thru 07-31-2025

df2 = filter_by_date_range(df2)

In [871]:
# Drop columns not needed for analysis
df2 = df2.drop(columns=["istransfer",   
"shelter",
"chip",
"name",
"age",
"location",
"istrial",
"returndate",
"returnedreason",
"deceaseddate",
"deceasedreason",
"diedoffshelter",
"putToSleep",
"isdoa"])

In [872]:
# verify columns were dropped
df2.columns

Index(['animalId', 'intakeDate', 'intakeReason', 'breed', 'color', 'species',
       'sex', 'outcomeDate', 'outcome', 'shelterName', 'shelterID', 'city',
       'state', 'indate', 'outdate'],
      dtype='object')

In [873]:
# check for missing data
df2.isna()

,animalId,intakeDate,intakeReason,breed,color,species,sex,outcomeDate,outcome,shelterName,shelterID,city,state,indate,outdate
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40893,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
40894,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
40895,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
40896,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
41341,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [874]:
# count of missing data
df2.isna().sum()

animalId         0
intakeDate       0
intakeReason     2
breed           75
color            0
species          0
sex              0
outcomeDate      0
outcome          0
shelterName      0
shelterID        0
city             0
state            0
indate           0
outdate          0
dtype: int64

In [875]:
# Fill missing data with simple placeholder text
# This avoids potential issues due to blanks
df2['intakeReason'] = df2['intakeReason'].fillna("unspecified")
df2['breed'] = df2['breed'].fillna("unknown")
df2['outcome'] = df2['outcome'].fillna('unknown')
df2['breed'] = df2['breed'].fillna("unknown")
df2['species'] = df2['species'].fillna('unspecified')

In [876]:
# count of missing data after filling in some columns
# missing data in outdate and outcome indicates animal remains in shelter
df2.isna().sum()

animalId        0
intakeDate      0
intakeReason    0
breed           0
color           0
species         0
sex             0
outcomeDate     0
outcome         0
shelterName     0
shelterID       0
city            0
state           0
indate          0
outdate         0
dtype: int64

In [877]:
# check for duplicates
df2.duplicated(keep = False)

19       False
20       False
21       False
22       False
23       False
         ...
40893    False
40894    False
40895    False
40896    False
41341    False
Length: 33974, dtype: bool

In [878]:
# count of duplicated data
df2.duplicated(keep = False).sum()

np.int64(186)

In [879]:
# drop duplicated rows
df2 = df2.drop_duplicates(keep="first")

In [880]:
# This calls the function that calculates the length of stay and adds it to the dataframe

df2 = add_length_of_stay(df2)

In [881]:
# verify final columns
df2.columns

Index(['animalId', 'intakeDate', 'intakeReason', 'breed', 'color', 'species',
       'sex', 'outcomeDate', 'outcome', 'shelterName', 'shelterID', 'city',
       'state', 'indate', 'outdate', 'lengthOfStay'],
      dtype='object')

In [882]:
# Count number of animals by type and outcome
outcome_table2 = df2.pivot_table(index='species', columns='outcome', aggfunc='size', fill_value=0)

print(outcome_table2)

outcome           Adoption  Escaped  Foster  Reclaimed  Released To Wild  \
species
Bird                    84        0       4         12                 2
Cat                  11760       15    6755        838                86
Chicken                  3        0       2          4                 1
Chinchilla               7        0       0          0                 0
Dog                   6465        5    2332       3276                 0
Ferret                   3        0       0          2                 0
Fish                    11        0       0          0                 0
Gerbil                  16        0       0          0                 1
Goat                     1        0       0          4                 0
Guinea Pig             232        0      15          0                 0
Hamster                  9        0       0          1                 0
Hedgehog                 9        0      10          0                 0
Horse                    1        0       0          3                 0
House Rabbit           336        0      93         10                 0
Livestock               42        0       8          5                 0
Lizard                  19        0       4          3                 0
Mouse                    5        0       0          4                 0
Opossum                  0        0       0          0                 0
Pig                      5        0       3          6                 0
Primate                  0        0       0          1                 0
Raccoon                  0        0       0          0                 0
Rat                    107        0       0          4                 0
Skunk                    0        0       0          0                 0
Snake                   15        1       1          9                 0
Squirrel                 0        0       0          0                 0
Sugar Glider             3        0       0          0                 0
Tarantula                1        0       0          0                 0
Terrapin                 0        0       0          0                 0
Tortoise                 1        0       0          2                 0
Turtle                   2        0       0          0                 2
Wildlife - other         4        0       0          0                 2

outcome           Retailer  Stolen  Transfer
species
Bird                     0       0        16
Cat                    311      16       476
Chicken                  0       0         0
Chinchilla               0       0         0
Dog                      0       2       167
Ferret                   0       0         9
Fish                     0       0         0
Gerbil                   0       0         3
Goat                     0       0         0
Guinea Pig               0       0         6
Hamster                  0       0        21
Hedgehog                 0       0         0
Horse                    0       0         0
House Rabbit             0       0        51
Livestock                0       0         2
Lizard                   0       0         3
Mouse                    0       0        29
Opossum                  0       0         6
Pig                      0       0         1
Primate                  0       0         0
Raccoon                  0       0         1
Rat                      0       0        61
Skunk                    0       0         1
Snake                    0       0         2
Squirrel                 0       0         2
Sugar Glider             0       0         4
Tarantula                0       0         0
Terrapin                 0       0         1
Tortoise                 0       0         0
Turtle                   0       0         9
Wildlife - other         0       0        14

# Load Intake and Outcome Data for Austin, TX and merge into one dataframe

In [883]:
# Load the two CSV files
# original austin files names have been shortened for easier use

intakes_df = pd.read_csv('../data/Austin_Animal_Center_Intakes.csv')
outcomes_df = pd.read_csv('../data/Austin_Animal_Center_Outcomes.csv')

In [884]:
# Combine the intake and outcome file where ALL intakes are listed and outcomes when they match

merged_df = pd.merge(intakes_df, outcomes_df, on='Animal ID', how='left')

# Make a copy of the data to work with
df3 = merged_df.copy()

In [885]:
# Verify it worked
df3.head()

,Animal ID,Name_x,DateTime_x,MonthYear_x,Found Location,Intake Type,Intake Condition,Animal Type_x,Sex upon Intake,Age upon Intake,...,Name_y,DateTime_y,MonthYear_y,Outcome Type,Outcome Subtype,Animal Type_y,Sex upon Outcome,Age upon Outcome,Breed_y,Color_y
0,A521520,Nina,10/01/2013 07:51:00 AM,October 2013,Norht Ec in Austin (TX),Stray,Normal,Dog,Spayed Female,7 years,...,Nina,2013-10-01T15:39:00,10-2013,Return to Owner,NaN,Dog,Spayed Female,7 years,Border Terrier/Border Collie,White/Tan
1,A664235,NaN,10/01/2013 08:33:00 AM,October 2013,Abia in Austin (TX),Stray,Normal,Cat,Unknown,1 week,...,NaN,2013-10-01T10:39:00,10-2013,Transfer,Partner,Cat,Unknown,1 week,Domestic Shorthair Mix,Orange/White
2,A664236,NaN,10/01/2013 08:33:00 AM,October 2013,Abia in Austin (TX),Stray,Normal,Cat,Unknown,1 week,...,NaN,2013-10-01T10:44:00,10-2013,Transfer,Partner,Cat,Unknown,1 week,Domestic Shorthair Mix,Orange/White
3,A664237,NaN,10/01/2013 08:33:00 AM,October 2013,Abia in Austin (TX),Stray,Normal,Cat,Unknown,1 week,...,NaN,2013-10-01T10:44:00,10-2013,Transfer,Partner,Cat,Unknown,1 week,Domestic Shorthair Mix,Orange/White
4,A664233,Stevie,10/01/2013 08:53:00 AM,October 2013,7405 Springtime in Austin (TX),Stray,Injured,Dog,Intact Female,3 years,...,Stevie,2013-10-01T15:33:00,10-2013,Euthanasia,Suffering,Dog,Intact Female,3 years,Pit Bull Mix,Blue/White

In [886]:
df3.tail()

,Animal ID,Name_x,DateTime_x,MonthYear_x,Found Location,Intake Type,Intake Condition,Animal Type_x,Sex upon Intake,Age upon Intake,...,Name_y,DateTime_y,MonthYear_y,Outcome Type,Outcome Subtype,Animal Type_y,Sex upon Outcome,Age upon Outcome,Breed_y,Color_y
222105,A929690,NaN,05/03/2025 11:18:00 PM,May 2025,8038 Exchange Dr in Austin (TX),Stray,Injured,Dog,Intact Male,2 years,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222106,A929717,NaN,05/04/2025 03:14:00 PM,May 2025,Austin (TX),Public Assist,Normal,Dog,Intact Male,1 year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222107,A929724,NaN,05/04/2025 07:43:00 PM,May 2025,7105 Providence Ave Apt 3 in Austin (TX),Stray,Normal,Other,Unknown,1 year,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222108,A929725,Oswold,05/04/2025 10:55:00 PM,May 2025,1501 Red River St in Austin (TX),Public Assist,Normal,Dog,Intact Male,10 years,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222109,A929635,NaN,05/04/2025 11:44:00 PM,May 2025,708 Simonetti in Austin (TX),Stray,Normal,Cat,Spayed Female,2 years,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [887]:
df3.describe()

,Animal ID,Name_x,DateTime_x,MonthYear_x,Found Location,Intake Type,Intake Condition,Animal Type_x,Sex upon Intake,Age upon Intake,...,Name_y,DateTime_y,MonthYear_y,Outcome Type,Outcome Subtype,Animal Type_y,Sex upon Outcome,Age upon Outcome,Breed_y,Color_y
count,222110,171164,222110,222110,222110,222110,222110,222110,222109,222110,...,170576,221246,221246,221178,87360,221246,221245,221237,221246,221246
unique,156287,29774,119722,140,70183,6,20,5,5,55,...,29674,145688,140,11,26,5,5,55,3002,660
top,A721033,Max,09/23/2016 12:00:00 PM,June 2015,Austin (TX),Stray,Normal,Dog,Intact Male,1 year,...,Max,2016-04-18T00:00:00-05:00,06-2019,Adoption,Partner,Dog,Neutered Male,1 year,Domestic Shorthair Mix,Black/White
freq,1089,1223,74,2715,45438,144422,192768,135941,68352,38133,...,1221,57,2828,108997,43920,135472,85759,38551,37582,23926

In [888]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 222110 entries, 0 to 222109
Data columns (total 23 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Animal ID         222110 non-null  object
 1   Name_x            171164 non-null  object
 2   DateTime_x        222110 non-null  object
 3   MonthYear_x       222110 non-null  object
 4   Found Location    222110 non-null  object
 5   Intake Type       222110 non-null  object
 6   Intake Condition  222110 non-null  object
 7   Animal Type_x     222110 non-null  object
 8   Sex upon Intake   222109 non-null  object
 9   Age upon Intake   222110 non-null  object
 10  Breed_x           222110 non-null  object
 11  Color_x           222110 non-null  object
 12  Date of Birth     221246 non-null  object
 13  Name_y            170576 non-null  object
 14  DateTime_y        221246 non-null  object
 15  MonthYear_y       221246 non-null  object
 16  Outcome Type      221178 non-null  object
 17  Outcome Subtype   87360 non-null   object
 18  Animal Type_y     221246 non-null  object
 19  Sex upon Outcome  221245 non-null  object
 20  Age upon Outcome  221237 non-null  object
 21  Breed_y           221246 non-null  object
 22  Color_y           221246 non-null  object
dtypes: object(23)
memory usage: 39.0+ MB

In [889]:
df3.columns

Index(['Animal ID', 'Name_x', 'DateTime_x', 'MonthYear_x', 'Found Location',
       'Intake Type', 'Intake Condition', 'Animal Type_x', 'Sex upon Intake',
       'Age upon Intake', 'Breed_x', 'Color_x', 'Date of Birth', 'Name_y',
       'DateTime_y', 'MonthYear_y', 'Outcome Type', 'Outcome Subtype',
       'Animal Type_y', 'Sex upon Outcome', 'Age upon Outcome', 'Breed_y',
       'Color_y'],
      dtype='object')

In [890]:
df3.shape

(222110, 23)

In [891]:
df3.dtypes

Animal ID           object
Name_x              object
DateTime_x          object
MonthYear_x         object
Found Location      object
Intake Type         object
Intake Condition    object
Animal Type_x       object
Sex upon Intake     object
Age upon Intake     object
Breed_x             object
Color_x             object
Date of Birth       object
Name_y              object
DateTime_y          object
MonthYear_y         object
Outcome Type        object
Outcome Subtype     object
Animal Type_y       object
Sex upon Outcome    object
Age upon Outcome    object
Breed_y             object
Color_y             object
dtype: object

## Data Clean Up
- Rename Columns
- Add Shelter information
- Call Function to convert date columns to datetime format
- Call Function to trim data set to specific date range
- Drop columns not needed for analysis
- Check for Missing Data
- Count of Missing Data
- Replace necessary missing data
- Check for duplicates
- Drop Duplicate Columns
- Drop Duplicate Rows
- Call Function for Length of Stay

In [892]:
# Rename columns to clearer names for use

df3.columns = [
    "animalId",
    "intakeName",
    "intakeDate",
    "intakeMonthYear",
    "foundLocation",
    "intakeReason",
    "intakeCondition",
    "species",
    "sex",
    "age",
    "breed",
    "color",
    "birthdate",
    "outcomeName",
    "outcomeDate",
    "outcomeMonthYear",
    "outcome",
    "outcomeSubtype",
    "outcomeAnimalType",
    "outcomeSex",
    "outcomeAge",
    "outcomeBreed",
    "outcomeColor"
]

In [893]:
# Add Shelter Name, Location and Shelter ID Column

df3['shelterName'] = 'Austin Animal Center'
df3['shelterID'] = 'TXAUAC01'
df3['city'] = 'Austin'
df3['state'] = 'TX'

In [894]:
# Verify column changes

df3.columns

Index(['animalId', 'intakeName', 'intakeDate', 'intakeMonthYear',
       'foundLocation', 'intakeReason', 'intakeCondition', 'species', 'sex',
       'age', 'breed', 'color', 'birthdate', 'outcomeName', 'outcomeDate',
       'outcomeMonthYear', 'outcome', 'outcomeSubtype', 'outcomeAnimalType',
       'outcomeSex', 'outcomeAge', 'outcomeBreed', 'outcomeColor',
       'shelterName', 'shelterID', 'city', 'state'],
      dtype='object')

In [895]:
# Call the function to convert date columns to datetime to do calculations

df3 = convert_date_columns(df3)

print(df3.indate, df3.outdate)

0        2013-10-01 07:51:00
1        2013-10-01 08:33:00
2        2013-10-01 08:33:00
3        2013-10-01 08:33:00
4        2013-10-01 08:53:00
                 ...
222105   2025-05-03 23:18:00
222106   2025-05-04 15:14:00
222107   2025-05-04 19:43:00
222108   2025-05-04 22:55:00
222109   2025-05-04 23:44:00
Name: indate, Length: 222110, dtype: datetime64[ns] 0        2013-10-01 15:39:00
1        2013-10-01 10:39:00
2        2013-10-01 10:44:00
3        2013-10-01 10:44:00
4        2013-10-01 15:33:00
                 ...
222105                   NaT
222106                   NaT
222107                   NaT
222108                   NaT
222109                   NaT
Name: outdate, Length: 222110, dtype: datetime64[ns]

In [896]:
# This calls the function that trims the dataframes to the time period of 01-01-2017 thru 07-31-2025

df3 = filter_by_date_range(df3)

In [897]:
# Drop columns not needed for analysis
df3 = df3.drop(columns=["intakeName",
"intakeMonthYear",
"foundLocation",
"intakeCondition",
"age",
"birthdate",
"outcomeName",
"outcomeMonthYear",
"outcomeSubtype",
"outcomeAnimalType",
"outcomeSex",
"outcomeAge",
"outcomeBreed",
"outcomeColor"])

In [898]:
# verify columns were dropped
df3.columns

Index(['animalId', 'intakeDate', 'intakeReason', 'species', 'sex', 'breed',
       'color', 'outcomeDate', 'outcome', 'shelterName', 'shelterID', 'city',
       'state', 'indate', 'outdate'],
      dtype='object')

In [899]:
# check for missing data
df3.isna()

,animalId,intakeDate,intakeReason,species,sex,breed,color,outcomeDate,outcome,shelterName,shelterID,city,state,indate,outdate
75672,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
75673,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
75674,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
75675,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
75676,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222061,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
222062,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
222063,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
222069,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
222103,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [900]:
# count of missing data
df3.isna().sum()

animalId         0
intakeDate       0
intakeReason     0
species          0
sex              0
breed            0
color            0
outcomeDate      0
outcome         61
shelterName      0
shelterID        0
city             0
state            0
indate           0
outdate          0
dtype: int64

In [901]:
# check for duplicates
df3.duplicated(keep = False)

75672     False
75673     False
75674     False
75675     False
75676     False
          ...
222061    False
222062    False
222063    False
222069    False
222103    False
Length: 139341, dtype: bool

In [902]:
# Fill missing data with simple placeholder text
# This avoids potential issues due to blanks
df3['intakeReason'] = df3['intakeReason'].fillna("unspecified")
df3['breed'] = df3['breed'].fillna("unknown")
df3['outcome'] = df3['outcome'].fillna('unknown')
df3['species'] = df3['species'].fillna('unspecified')

In [903]:
# count of missing data after filling in some columns
# missing data in outdate and outcome indicates animal remains in shelter
df3.isna().sum()

animalId        0
intakeDate      0
intakeReason    0
species         0
sex             0
breed           0
color           0
outcomeDate     0
outcome         0
shelterName     0
shelterID       0
city            0
state           0
indate          0
outdate         0
dtype: int64

In [904]:
# count of duplicated data
df3.duplicated(keep = False).sum()

np.int64(168)

In [905]:
# drop duplicated rows
df3 = df3.drop_duplicates(keep="first")

In [906]:
# Validate count of duplicated data after drop of duplicate rows 
df3.duplicated(keep = False).sum()

np.int64(0)

In [907]:
# This calls the function that calculates the length of stay and adds it to the dataframe

df3 = add_length_of_stay(df3)

In [908]:
# verify final columns
df3.columns

Index(['animalId', 'intakeDate', 'intakeReason', 'species', 'sex', 'breed',
       'color', 'outcomeDate', 'outcome', 'shelterName', 'shelterID', 'city',
       'state', 'indate', 'outdate', 'lengthOfStay'],
      dtype='object')

In [ ]:
 #Create a combined csv file for future use

# df3.to_csv("austin_animal_data_combined.csv", index=False)

In [909]:
# Count number of animals by type and outcome
outcome_table3 = df3.pivot_table(index='species', columns='outcome', aggfunc='size', fill_value=0)

print(outcome_table3)

outcome    Adoption  Died  Disposal  Euthanasia  Lost  Missing  Relocate  \
species
Bird            233    29        16          93     1        0         4
Cat           29108   680       145        1362     0       28         6
Dog           44939   285        97         953     1       27         2
Livestock        15     1         0           2     0        0         0
Other           945   130       381        3599     0        5         2

outcome    Return to Owner  Rto-Adopt  Stolen  Transfer  unknown
species
Bird                    50          0       0       181        1
Cat                   2107        299       0     15773       11
Dog                  20867       1806      10     14243       44
Livestock                5          0       0         3        0
Other                   48          3       0       694        2

## Connect to the SQLite database (creates if it doesn't exist)

In [910]:
conn = sqlite3.connect('../data/animal_shelter_analysis.db')
cursor = conn.cursor()

# Enable FK constraints
cursor.execute("PRAGMA foreign_keys = ON;")

## Create SQL Lite tables
- Animal
- Shelter
- Intake
- Outcome
- Species

In [911]:
# Create the Animal table
create_table_sql = """
CREATE TABLE IF NOT EXISTS Animal (
    animalID TEXT PRIMARY KEY,
    breed TEXT,
    color TEXT,
    sex TEXT,
    species TEXT,
    lengthOfStay INTEGER
);
"""

cursor.execute(create_table_sql)
conn.commit()

In [920]:
# Create the Shelter table
create_table_sql = """
CREATE TABLE IF NOT EXISTS Shelter (
    shelterID TEXT PRIMARY KEY,
    name TEXT,
    city TEXT,
    state TEXT,
    animalID TEXT,
    
    FOREIGN KEY (animalID) REFERENCES Animal(animalID)
);
"""

cursor.execute(create_table_sql)
conn.commit()

In [921]:
# Create the Species table
create_table_sql = """
CREATE TABLE IF NOT EXISTS Species (
    speciesID INTEGER PRIMARY KEY AUTOINCREMENT,
    speciesType TEXT,
    animalID TEXT,
    shelterID TEXT,
    
    FOREIGN KEY (animalID) REFERENCES Animal(animalID),
    FOREIGN KEY (shelterID) REFERENCES Shelter(shelterID)
);
"""

cursor.execute(create_table_sql)
conn.commit()

In [922]:
# Create the Intake table
create_table_sql = """
CREATE TABLE IF NOT EXISTS Intake (
    intakeID INTEGER PRIMARY KEY AUTOINCREMENT,
    intakeDate DATE,
    intakeReason TEXT,
    indate DATE,
    animalID TEXT,
    shelterID TEXT,
    speciesID INTEGER,

    FOREIGN KEY (animalID) REFERENCES Animal(animalID),
    FOREIGN KEY (shelterID) REFERENCES Shelter(shelterID),
    FOREIGN KEY (speciesID) REFERENCES Species(speciesID)
);
"""

cursor.execute(create_table_sql)
conn.commit()

In [ ]:
# Create the Outcome table
create_table_sql = """
CREATE TABLE IF NOT EXISTS Outcome (
    outcomeID INTEGER PRIMARY KEY AUTOINCREMENT,
    outcomeDate DATE,
    outcome TEXT,
    outdate DATE,
    animalID TEXT,
    shelterID TEXT,
    speciesID INTEGER,

    FOREIGN KEY (animalID) REFERENCES Animal(animalID),
    FOREIGN KEY (shelterID) REFERENCES Shelter(shelterID),
    FOREIGN KEY (speciesID) REFERENCES Species(speciesID)
);
"""

cursor.execute(create_table_sql)
conn.commit()

In [923]:
# Verify the tables exist
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('sqlite_sequence',), ('Animal',), ('Outcome',), ('Shelter',), ('Species',), ('Intake',)]

## Load the database and tables from the dataframes