## CSV files used in this notebook to load animal shelter data
1. Yearly shelter data (2021 - 2025) CSV file kentucky_shelter_data.csv (provided in data/) 
Downloaded from the Louisville Metro site https://data.louisvilleky.gov

2. Yearly shelter data (2017 - 2025) CSV file BloomingtonIN_Animal_Shelter_Animals.csv (provided in data/) Downloaded from the City of Bloomington site https://data.bloomington.in.gov

3. Yearly shelter data (2013-2025)CSV files Austin_Animal_Center_Intakes.csv and Austin_Anima_Center_Outcomes (provided in data/) 
Downloaded from the City of Austin open data portal site https://data.austintexas.gov

## Functions included in this notebook
1. convert_date_columns : converts date fields to a datetime in order to do calculations
2. add_length_of_stay : calculates the length of stay in the shelter for each intake
3. filter_by_date_range : trims the dataframes to the specified time period to reduce # of rows
4. load_dataframe_to_tables : loads the SQL Lite tables one at a time using the defined dictionary
5. categorize_intake_reason : adds a standardized intake category column for reporting
6. categorize_outcome : adds a standardized outcome category column for reporting

# Notes:
# The function add_length_of_stay was a bit difficult due to the result being a timedelta
- Pandas Timedelta internally uses nanoseconds.
- If you don’t convert .dt.days to an integer type, Pandas may still treat it as a timedelta-like object.
- SQLite doesn’t have a native timedelta type, so it stores the raw representation (nanoseconds).
- Combining the steps did not work and still caused the dType to be timedelta.
- I had to break each piece into seperate steps in order order to get this work.  
- ChatGPT, CoPilot and I spent several hours trying different combinations until we got one to work.

# The functions categorize_intake_reason and categorize_outcome
- These were added after the inital SQL Lite table load and a SELECT DISTINCT on the intakeReason and outcome was done
- I used AI to help map the categories to save time

## SQL Lite

# Database Name
- animalshelterdata.db

# Tables Created
- Animal
- Shelter
- Intake
- Outcome
- Species

# ERD can be found in the additional documents folder

## SQL queries included in this notebook

- Include at least three intermediate/advanced SQL queries (joins, grouping/aggregation, having, subqueries, etc.).
1. most common intake reason by species 
2. average length of stay for each species by shelter


# Notes:
1.  most common intake reason by species
- Google, StackOverflow and AI was consulted because SQL Lite doesn't allow MAX(COUNT(*)) directly in a subquery

## Visualizations included 

- Include at least three different chart types in your notebook.
- Visuals must be well-designed, labeled, and help tell a clear story.

In [1032]:
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np 
import seaborn as sns
import sqlite3

In [1031]:
# FOR TESTING PURPOSES ONLY !!!!!!
# this will delete the dataframes so you can run the program multiple times 
del df, df2, df3

## Functions used in Data Wrangling

In [1033]:
# This function converts date fields to a datetime in order to do calculations
# Must be run after columns are renamed

def convert_date_columns(df, intake_col="intakeDate", outcome_col="outcomeDate"):

    df["indate"] = pd.to_datetime(df[intake_col], errors="coerce")
    df["outdate"] = pd.to_datetime(df[outcome_col], errors="coerce")
    
    return df

In [1034]:
# This function calculates the length of stay in the shelter for each intake
# Must be run after columns are renamed and the convert_date_columns function.

def add_length_of_stay(df):
    
    # Make sure the dates are datetime
    df["indate"] = pd.to_datetime(df["indate"], errors="coerce")
    df["outdate"] = pd.to_datetime(df["outdate"], errors="coerce")

    # Calculate timedelta
    df["lengthOfStay"] = df["outdate"] - df["indate"]

    # Convert timedelta to integer days
    df["lengthOfStay"] = df["lengthOfStay"].dt.days

    # Fill missing values with 0 and convert to Int64 (SQLite compatible)
    df["lengthOfStay"] = df["lengthOfStay"].fillna(0).astype("Int64")
    
    return df

In [1035]:
# This function trims the dataframes to the time period of 01-01-2017 thru 07-31-2025
# Must be run after columns are renamed and the convert_date_columns function

def filter_by_date_range(df, start_date="2023-01-01", end_date="2025-07-31"):
    df["indate"] = pd.to_datetime(df["indate"], errors='coerce')
    df["outdate"] = pd.to_datetime(df["outdate"], errors='coerce')
    return df[
        (df["indate"] >= start_date) & (df["indate"] <= end_date) &
        (df["outdate"] >= start_date) & (df["outdate"] <= end_date)
    ]

    return df

In [1036]:
# Add Intake Category column to the dataframe in order to group the different reasons into reportable data

def categorize_intake_reason(df, reason_col="intakeReason", new_col="intakeCategory"):

    # Normalize for matching
    normalized = df[reason_col].astype(str).str.strip().str.lower()

    df[new_col] = (
        normalized
        .map({

            # Owner Surrender – Non-Behavior
            "allergies": "Owner Surrender - Non-Behavioral",
            "financial constraints": "Owner Surrender - Non-Behavioral",
            "housing": "Owner Surrender - Non-Behavioral",
            "landlord issues": "Owner Surrender - Non-Behavioral",
            "marriage/relationship split": "Owner Surrender - Non-Behavioral",
            "medical": "Owner Surrender - Non-Behavioral",
            "moving": "Owner Surrender - Non-Behavioral",
            "owner surrender": "Owner Surrender - Non-Behavioral",
            "owner sur": "Owner Surrender - Non-Behavioral",
            "owner deceased": "Owner Surrender - Non-Behavioral",
            "unable to afford": "Owner Surrender - Non-Behavioral",
            "unsuitable accommodation": "Owner Surrender - Non-Behavioral",

            # Behavioral
            "behavior": "Owner Surrender - Behavioral",
            "biting": "Owner Surrender - Behavioral",
            "incompatible with other pets": "Owner Surrender - Behavioral",
            "incompatible with owner lifestyle": "Owner Surrender - Behavioral",
            "return adopt - behavior": "Owner Surrender - Behavioral",
            "return adopt - incompatible with other pets": "Owner Surrender - Behavioral",
            "return adopt - incompatible with owner lifestyle": "Owner Surrender - Behavioral",
            "return adopt - lifestyle issue": "Owner Surrender - Behavioral",

            # Stray / Found
            "found": "Stray",
            "stray": "Stray",
            "tnr - trap/neuter/release": "Stray",
            
           # Wildlife
            "injured wildlife": "Wildlife",
            "wildlife": "Wildlife",

            # Confiscation / Legal
            "confiscate": "Legal Confiscation",
            "impound or seizure": "Legal Confiscation",
            "police assist": "Legal Confiscation",
            "public assist": "Legal Confiscation",
            "rabies monitoring": "Legal Confiscation",

            # Transfer
            "transfer from other shelter": "Transfer",
            "for transp": "Transfer",
            "foster": "Transfer",
            "return": "Transfer",

            # Euthanasia
            "doa": "Euthanasia",
            "disposal": "Euthanasia",
            "euthanasia request": "Euthanasia",
            "owner requested euthanasia": "Euthanasia",

            # Abandoned / Neglect
            "abandoned": "Abandoned Neglect",
            "abuse/ neglect": "Abandoned Neglect",

            # Litter / Offspring
            "born in shelter": "Offspring",
            "litter relinquishment": "Offspring",

        })
        .fillna("Other")
    )

    return df

In [1037]:
# Add Outcome Category column to the dataframe in order to group the different outcomes into reportable data

def categorize_outcome(df, outcome_col="outcome", new_col="outcomeCategory"):
   
    # Normalize values for matching
    normalized = df[outcome_col].astype(str).str.strip().str.lower()

    df[new_col] = (
        normalized.map({

            # Adoption
            "adoption": "Adoption",
            "rto-adopt": "Adoption",

            # Return to Owner
            "rto": "Return to Owner",
            "return to owner": "Return to Owner",
            "reclaimed": "Return to Owner",

            # Foster
            "foster": "Foster",

            # Transfer
            "transfer": "Transfer",
            "transport": "Transfer",
            "retailer": "Transfer",

            # Trap-Neuter-Return / community cat programs
            "tnr": "TNR",
            "rtf": "TNR",
            "snr": "TNR",

            # Wild release or relocate
            "released to wild": "Wild Release",
            "release": "Wild Release",
            "relocate": "Wild Release",

            # Found after missing
            "found exp": "Reunited",

            # Died / euthanasia / disposal
            "died": "Died",
            "died ": "Died",
            "euth": "Euthanized",
            "euthanasia": "Euthanized",
            "disposal": "Died",
            "disposal ": "Died",

            # Lost or stolen
            "lost": "Lost",
            "missing": "Lost",
            "stolen": "Stolen",

            # Escape
            "escaped": "Escaped",

            # Unknown
            "unknown": "Unknown"

        }).fillna("Unknown")
    )

    return df

# Load dataset from Louisville, KY

In [1038]:
# Read in the csv file
# original csv file name was shortened for easier use

data = pd.read_csv('../data/kentucky_shelter_data.csv')

# Make a copy of the data to work with
df = data.copy()

# Preview and Analyze the data structure

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.describe()

In [ ]:
df.info()

In [ ]:
df.columns

In [ ]:
df.shape

In [ ]:
df.dtypes

## Data Clean Up
- Rename Columns
- Add Shelter information
- Drop columns not needed for analysis
- Check for Missing Data
- Count of Missing Data
- Replace necessary missing data
- Call Function to convert date columns to datetime format
- Call Function to trim data set to specific date range
- Check for duplicates
- Drop Duplicate Columns
- Drop Duplicate Rows
- Call Function for Length of Stay

In [1039]:
# Rename columns to clearer names for use
df.columns = ["kennelId",
"animalId",
"jurisdiction",
"intakeReason",
"intakeSubtype",
"intakeDate",
"surreason",
"outcome",
"outcomeSubtype",
"outcomeDate",
"species",
"sex",
"bites",
"petsize",
"color",
"breed",
"zipcode",
"objectId"
]

In [ ]:
# Convert species to lowercase, strip spaces
df['species'] = df['species'].astype(str).str.strip().str.lower()

df.head()

,kennelId,animalId,jurisdiction,intakeReason,intakeSubtype,intakeDate,surreason,outcome,outcomeSubtype,outcomeDate,species,sex,bites,petsize,color,breed,zipcode,objectId
0,408,A688221,40216,STRAY,OTC,2021-01-17 00:00:00,STRAY,TRANSPORT,RESCUE GRP,2021-02-06 00:00:00,dog,M,N,PUPPY,BR BRINDLE,CHIHUAHUA SH / MIX,40218,1
1,ID07,A688234,40222,STRAY,OTC,2021-01-18 00:00:00,STRAY,RTO,IN FIELD,2021-01-18 00:00:00,dog,N,N,MED,BR BRINDLE / WHITE,BOSTON TERRIER / MIX,40205,2
2,DW13,A688337,40118,STRAY,OTC,2021-01-21 00:00:00,STRAY,RTO,IN KENNEL,2021-01-23 00:00:00,dog,S,N,LARGE,WHITE / BROWN,CATAHOULA / MIX,40118,3
3,INTAKE,A688419,40204,STRAY,OTC,2021-02-03 00:00:00,STRAY,TNR,CARETAKER,2021-02-04 00:00:00,cat,S,N,MED,BLK TABBY,DOMESTIC SH,40204,4
4,INTAKE,A688478,40214,STRAY,OTC,2021-02-10 00:00:00,STRAY,TNR,CARETAKER,2021-02-11 00:00:00,cat,N,N,MED,TORTIE,DOMESTIC SH,40210,5

In [1041]:
# Add Shelter Name, Location and Shelter ID Column

df['shelterName'] = 'Louisville Metro Animal Services'
df['shelterID'] = 'KYLMAS01'
df['city'] = 'Louisville'
df['state'] = 'KY'

In [1042]:
# Drop columns not needed for analysis
df = df.drop(columns=["kennelId", "jurisdiction", "intakeSubtype", "surreason", "outcomeSubtype", "bites", "petsize", "zipcode", "objectId"])

In [1043]:
# Verify column changes
df.columns

Index(['animalId', 'intakeReason', 'intakeDate', 'outcome', 'outcomeDate',
       'species', 'sex', 'color', 'breed', 'shelterName', 'shelterID', 'city',
       'state'],
      dtype='object')

In [1044]:
# check for missing data
df.isna()

,animalId,intakeReason,intakeDate,outcome,outcomeDate,species,sex,color,breed,shelterName,shelterID,city,state
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
60338,False,False,False,False,False,False,False,False,False,False,False,False,False
60339,False,False,False,False,False,False,False,False,False,False,False,False,False
60340,False,False,False,True,True,False,False,False,False,False,False,False,False
60341,False,False,False,False,False,False,False,False,False,False,False,False,False
60342,False,False,False,False,False,False,False,False,False,False,False,False,False

In [1045]:
# count of missing data
df.isna().sum()

animalId            0
intakeReason        0
intakeDate          0
outcome         13588
outcomeDate     13554
species             0
sex              1025
color               1
breed              76
shelterName         0
shelterID           0
city                0
state               0
dtype: int64

In [1046]:
# Fill missing data with simple placeholder text
# This avoids potential issues due to blanks
df['color'] = df['color'].fillna("unspecified")
df['breed'] = df['breed'].fillna("unknown")
df['sex'] = df['sex'].fillna("unknown")
df['species'] = df['species'].fillna('unspecified')
df['outcome'] = df['outcome'].fillna('unknown')
df['outcomeDate'] = df['outcomeDate'].fillna(0)

In [1047]:
# count of missing data after filling in some columns
# missing data in outdate and outcome indicates animal remains in shelter
df.isna().sum()

animalId        0
intakeReason    0
intakeDate      0
outcome         0
outcomeDate     0
species         0
sex             0
color           0
breed           0
shelterName     0
shelterID       0
city            0
state           0
dtype: int64

In [1048]:
# Call the function to convert date columns to datetime to do calculations
df = convert_date_columns(df)

print(df.indate, df.outdate)

0       2021-01-17
1       2021-01-18
2       2021-01-21
3       2021-02-03
4       2021-02-10
           ...
60338   2023-08-11
60339   2023-08-15
60340   2023-08-18
60341   2023-08-19
60342   2024-06-28
Name: indate, Length: 60343, dtype: datetime64[ns] 0       2021-02-06
1       2021-01-18
2       2021-01-23
3       2021-02-04
4       2021-02-11
           ...
60338   2023-10-03
60339   2023-09-18
60340          NaT
60341   2023-08-29
60342   2024-07-03
Name: outdate, Length: 60343, dtype: datetime64[ns]

In [1049]:
# This calls the function that trims the dataframes to the time period of 01-01-2017 thru 07-31-2025
df = filter_by_date_range(df)

In [1050]:
# verify the number of rows and columns after the filtering of date range
df.shape

(28485, 15)

In [1051]:
# check for duplicates
df.duplicated(keep = False)

29       False
35       False
41       False
43       False
47       False
         ...
60337    False
60338    False
60339    False
60341    False
60342    False
Length: 28485, dtype: bool

In [1052]:
# count of duplicated data
df.duplicated(keep = False).sum()

np.int64(44)

In [1053]:
# There can be duplicates on Animal Id due to more than one intake event happening.
# I have decided to keep the latest intake event for anaylsis.

df.drop_duplicates(subset='animalId', keep='last', inplace=True)

In [1054]:
# This calls the function to create the Intake Categories 
df = categorize_intake_reason(df)

print(df["intakeCategory"].head())

29                               Stray
35                  Legal Confiscation
43                               Stray
47                               Stray
59    Owner Surrender - Non-Behavioral
Name: intakeCategory, dtype: object

In [1055]:
# This calls the function to create the Outcome Categories 
df = categorize_outcome(df)

print(df["outcomeCategory"].head())

29    Return to Owner
35           Adoption
43    Return to Owner
47    Return to Owner
59           Adoption
Name: outcomeCategory, dtype: object

In [1056]:
# This calls the function that calculates the length of stay and adds it to the dataframe

df = add_length_of_stay(df)

In [1057]:
# This is for testing purposes

print(df["lengthOfStay"].head())
print(df["lengthOfStay"].dtype)

29     0
35    61
43    13
47     2
59    12
Name: lengthOfStay, dtype: Int64
Int64

In [ ]:
# verify final columns

df.columns

In [1058]:
# verify the number of rows and columns

df.shape

(21130, 18)

In [1059]:
# Count number of animals by type and outcome just as a quick validation
outcome_table = df.pivot_table(index='species', columns='outcome', aggfunc='size', fill_value=0)

print(outcome_table)

outcome     ADOPTION  DIED  DISPOSAL  EUTH  FOSTER  FOUND EXP  LOST  RELEASE  \
species
bird              31     3         8     4       1          0     0        0
cat             2103   177       114   615    1328          0     4        0
dog             3598    45       158  1082    1502          2    23        1
guinea pig         0     0         0     0       1          0     0        0
livestock          2     0         4     0       1          0     0        0
other              6     3        25    65       3          0     0        0
rabbit             5     2         0     2      19          0     0        0

outcome     RTF   RTO   SNR   TNR  TRANSFER  TRANSPORT  unknown
species
bird          0     2     0     0        18          0        5
cat         499   256  3085  1708       871          1        4
dog           0  2476     0     1      1160          3        3
guinea pig    0     1     0     0         3          0        0
livestock     0     4     0     0        12          0        0
other         0     1     0     0         1          0        0
rabbit        0     2     0     0        77          0        0

# Load dataset from Bloomington, IN

In [1060]:
# Read in the csv file
data2 = pd.read_csv('../data/BloomingtonIN_Animal_Shelter_Animals.csv')

# Make a copy of the data to work with
df2 = data2.copy()

# Preview and Analyze the data structure

In [ ]:
df2.head()

In [ ]:
df2.tail()

In [ ]:
df2.describe()

In [ ]:
df2.info()

In [ ]:
df2.columns

In [ ]:
df2.shape

In [ ]:
df2.dtypes

## Data Clean Up
- Rename Columns
- Add Shelter information to dataframe
- Drop columns not needed for analysis
- Check / Count for Missing Data
- Replace missing data
- Call Function to convert date columns to datetime format
- Call Function to trim data set to specific date range
- Check for duplicates
- Drop Duplicate Columns
- Drop Duplicate Rows
- Call Function for Length of Stay

In [1061]:
# Rename columns to clearer names for use
df2.columns = ["animalId", 
"intakeDate",
"intakeReason", 
"istransfer",
"shelter",
"chip",
"name",
"breed",
"color",
"species",
"age",
"sex",
"location",
"outcomeDate",
"outcome",
"istrial",
"returndate",
"returnedreason",
"deceaseddate",
"deceasedreason",
"diedoffshelter",
"putToSleep",
"isdoa"]

In [1062]:
# Convert species to lowercase, strip spaces
df2['species'] = df2['species'].astype(str).str.strip().str.lower()

df2.head()

,animalId,intakeDate,intakeReason,istransfer,shelter,chip,name,breed,color,species,...,outcomeDate,outcome,istrial,returndate,returnedreason,deceaseddate,deceasedreason,diedoffshelter,putToSleep,isdoa
0,15801,11/28/2009 12:00:00 AM,Moving,False,C09115463,0A115D7358,Jadzia,Domestic Short Hair,Tortoiseshell,cat,...,05/13/2017 12:00:00 AM,Adoption,False,10/31/2024 12:00:00 AM,Owner requested Euthanasia,10/31/2024 12:00:00 AM,Owner Requested,False,True,False
1,15932,12/08/2009 12:00:00 AM,Moving,False,D09125594,0A11675477,Gonzo,German Shepherd Dog/Mix,Tan,dog,...,04/24/2017 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False
2,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,dog,...,04/15/2017 12:00:00 AM,Adoption,False,02/28/2020 12:00:00 AM,Stray,06/28/2024 12:00:00 AM,Court Order/ Legal,True,False,False
3,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,dog,...,02/29/2020 12:00:00 AM,Reclaimed,False,11/06/2023 12:00:00 AM,Stray,06/28/2024 12:00:00 AM,Court Order/ Legal,True,False,False
4,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,dog,...,12/17/2023 12:00:00 AM,Adoption,False,NaN,Stray,06/28/2024 12:00:00 AM,Court Order/ Legal,True,False,False

In [1063]:
# Add Shelter Name, Location and Shelter ID Column

df2['shelterName'] = 'Bloomington Animal Services'
df2['shelterID'] = 'INBLAS01'
df2['city'] = 'Bloomington'
df2['state'] = 'IN'

In [1064]:
# Verify name change

df2.columns

Index(['animalId', 'intakeDate', 'intakeReason', 'istransfer', 'shelter',
       'chip', 'name', 'breed', 'color', 'species', 'age', 'sex', 'location',
       'outcomeDate', 'outcome', 'istrial', 'returndate', 'returnedreason',
       'deceaseddate', 'deceasedreason', 'diedoffshelter', 'putToSleep',
       'isdoa', 'shelterName', 'shelterID', 'city', 'state'],
      dtype='object')

In [1065]:
# Drop columns not needed for analysis
df2 = df2.drop(columns=["istransfer",   
"shelter",
"chip",
"name",
"age",
"location",
"istrial",
"returndate",
"returnedreason",
"deceaseddate",
"deceasedreason",
"diedoffshelter",
"putToSleep",
"isdoa"])

In [1066]:
# verify columns were renamed and dropped
df2.columns

Index(['animalId', 'intakeDate', 'intakeReason', 'breed', 'color', 'species',
       'sex', 'outcomeDate', 'outcome', 'shelterName', 'shelterID', 'city',
       'state'],
      dtype='object')

In [1067]:
# check for missing data
df2.isna()

,animalId,intakeDate,intakeReason,breed,color,species,sex,outcomeDate,outcome,shelterName,shelterID,city,state
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
41382,False,False,False,False,False,False,False,False,False,False,False,False,False
41383,False,False,False,False,False,False,False,False,False,False,False,False,False
41384,False,False,False,False,False,False,False,False,False,False,False,False,False
41385,False,False,False,False,False,False,False,False,False,False,False,False,False
41386,False,False,False,False,False,False,False,False,False,False,False,False,False

In [1068]:
# count of missing data
df2.isna().sum()

animalId           0
intakeDate         0
intakeReason       2
breed             77
color              0
species            0
sex                0
outcomeDate     6588
outcome         6588
shelterName        0
shelterID          0
city               0
state              0
dtype: int64

In [1069]:
# Fill missing data with simple placeholder text
# This avoids potential issues due to blanks
df2['intakeReason'] = df2['intakeReason'].fillna("unspecified")
df2['breed'] = df2['breed'].fillna("unknown")
df2['outcome'] = df2['outcome'].fillna('unknown')
df2['breed'] = df2['breed'].fillna("unknown")
df2['species'] = df2['species'].fillna('unspecified')
df2['sex'] = df2['sex'].fillna('unknown')
df2['outcomeDate'] = df2['outcomeDate'].fillna(0)

In [1070]:
# count of missing data after filling in some columns
# missing data in outdate and outcome indicates animal remains in shelter
df2.isna().sum()

animalId        0
intakeDate      0
intakeReason    0
breed           0
color           0
species         0
sex             0
outcomeDate     0
outcome         0
shelterName     0
shelterID       0
city            0
state           0
dtype: int64

In [1071]:
# Call the function to convert date columns to datetime to do calculations

df2 = convert_date_columns(df2)

print(df2.indate, df2.outdate)

/var/folders/6j/ng0s8_v10mj7kwbwccbbwd840000gn/T/ipykernel_58620/570169243.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["indate"] = pd.to_datetime(df[intake_col], errors="coerce")

0       2009-11-28 00:00:00
1       2009-12-08 00:00:00
2       2012-08-10 00:00:00
3       2012-08-10 00:00:00
4       2012-08-10 00:00:00
                ...
41382   2025-09-18 11:31:53
41383   2025-09-19 11:13:42
41384   2025-09-19 15:38:02
41385   2025-09-19 16:33:01
41386   2025-09-22 12:18:36
Name: indate, Length: 41387, dtype: datetime64[ns] 0       2017-05-13
1       2017-04-24
2       2017-04-15
3       2020-02-29
4       2023-12-17
           ...
41382   2025-09-18
41383   2025-09-25
41384   2025-09-20
41385   2025-09-20
41386   2025-09-23
Name: outdate, Length: 41387, dtype: datetime64[ns]

/var/folders/6j/ng0s8_v10mj7kwbwccbbwd840000gn/T/ipykernel_58620/570169243.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["outdate"] = pd.to_datetime(df[outcome_col], errors="coerce")

In [1072]:
# This calls the function that trims the dataframes to the time period of 01-01-2017 thru 07-31-2025

df2 = filter_by_date_range(df2)

In [1073]:
# verify the number of rows and columns

df2.shape

(10582, 15)

In [1074]:
# check for duplicates
df2.duplicated(keep = False)

26841    False
26842    False
26843    False
26844    False
26845    False
         ...
40893    False
40894    False
40895    False
40896    False
41341    False
Length: 10582, dtype: bool

In [1075]:
# count of duplicated data
df2.duplicated(keep = False).sum()

np.int64(150)

In [1076]:
# There can be duplicates on Animal Id due to more than one intake event happening.
# I have decided to keep the latest intake event for anaylsis 

df2.drop_duplicates(subset=['animalId'], keep='last', inplace=True)

In [1077]:
# count of duplicated data
df2.duplicated(keep = False).sum()

np.int64(0)

In [1078]:
# This calls the function to create the Intake Categories 
df2 = categorize_intake_reason(df2)

print(df2["intakeCategory"].head())

26841                Stray
26842                Stray
26843    Abandoned Neglect
26844                Stray
26845                Stray
Name: intakeCategory, dtype: object

In [1079]:
# This calls the function to create the Outcome Categories 
df2 = categorize_outcome(df2)

print(df2["outcomeCategory"].head())

26841    Return to Owner
26842           Adoption
26843    Return to Owner
26844           Adoption
26845    Return to Owner
Name: outcomeCategory, dtype: object

In [1080]:
# This calls the function that calculates the length of stay and adds it to the dataframe

df2 = add_length_of_stay(df2)

In [1082]:
# This is for testing purposes

print(df2["lengthOfStay"].head())
print(df2["lengthOfStay"].dtype)

26841    -1
26842    11
26843     2
26844    11
26845    -1
Name: lengthOfStay, dtype: Int64
Int64

In [1081]:
# verify final columns
df2.columns

Index(['animalId', 'intakeDate', 'intakeReason', 'breed', 'color', 'species',
       'sex', 'outcomeDate', 'outcome', 'shelterName', 'shelterID', 'city',
       'state', 'indate', 'outdate', 'intakeCategory', 'outcomeCategory',
       'lengthOfStay'],
      dtype='object')

In [1083]:
# verify the number of rows and columns

df2.shape

(6386, 18)

In [1084]:
# Count number of animals by type and outcome
outcome_table2 = df2.pivot_table(index='species', columns='outcome', aggfunc='size', fill_value=0)

print(outcome_table2)

outcome           Adoption  Escaped  Foster  Reclaimed  Released To Wild  \
species
bird                    21        0       0          4                 1
cat                   3240        2     230        201                18
chinchilla               3        0       0          0                 0
dog                   1646        0      49        684                 0
fish                     5        0       0          0                 0
gerbil                   0        0       0          0                 0
guinea pig              39        0       0          0                 0
hamster                  3        0       0          1                 0
horse                    1        0       0          2                 0
house rabbit            50        0       3          3                 0
livestock               10        0       0          1                 0
lizard                   8        0       0          3                 0
mouse                    0        0       0          0                 0
pig                      0        0       0          2                 0
primate                  0        0       0          1                 0
skunk                    0        0       0          0                 0
snake                    5        0       0          3                 0
squirrel                 0        0       0          0                 0
turtle                   0        0       0          0                 0
wildlife - other         2        0       0          0                 1

outcome           Retailer  Stolen  Transfer
species
bird                     0       0         1
cat                     14       1        62
chinchilla               0       0         0
dog                      0       0        39
fish                     0       0         0
gerbil                   0       0         2
guinea pig               0       0         0
hamster                  0       0         0
horse                    0       0         0
house rabbit             0       0         2
livestock                0       0         0
lizard                   0       0         0
mouse                    0       0        18
pig                      0       0         0
primate                  0       0         0
skunk                    0       0         1
snake                    0       0         0
squirrel                 0       0         1
turtle                   0       0         3
wildlife - other         0       0         0

# Load Intake and Outcome Data for Austin, TX and merge into one dataframe

In [1085]:
# Load the two CSV files
# original austin files names have been shortened for easier use

intakes_df = pd.read_csv('../data/Austin_Animal_Center_Intakes.csv')
outcomes_df = pd.read_csv('../data/Austin_Animal_Center_Outcomes.csv')

In [1086]:
# Combine the intake and outcome file where ALL intakes are listed and outcomes when they match

merged_df = pd.merge(intakes_df, outcomes_df, on='Animal ID', how='left')

# Make a copy of the data to work with
df3 = merged_df.copy()

In [ ]:
# Verify it worked
df3.head()

In [ ]:
df3.tail()

In [ ]:
df3.describe()

In [ ]:
df3.info()

In [ ]:
df3.columns

In [ ]:
df3.dtypes

In [ ]:
df3.shape

## Data Clean Up
- Rename Columns
- Add Shelter information
- Drop columns not needed for analysis
- Check for Missing Data
- Count of Missing Data
- Replace necessary missing data
- Call Function to convert date columns to datetime format
- Call Function to trim data set to specific date range
- Add A to the animalId to avoid duplicates with LMAS data
- Check for duplicates
- Drop Duplicate Columns
- Drop Duplicate Rows
- Call Function for Length of Stay

In [1087]:
# Rename columns to clearer names for use

df3.columns = [
    "animalId",
    "intakeName",
    "intakeDate",
    "intakeMonthYear",
    "foundLocation",
    "intakeReason",
    "intakeCondition",
    "species",
    "sex",
    "age",
    "breed",
    "color",
    "birthdate",
    "outcomeName",
    "outcomeDate",
    "outcomeMonthYear",
    "outcome",
    "outcomeSubtype",
    "outcomeAnimalType",
    "outcomeSex",
    "outcomeAge",
    "outcomeBreed",
    "outcomeColor"
]

In [1088]:
# Convert species to lowercase, strip spaces
df3['species'] = df3['species'].astype(str).str.strip().str.lower()

df3.head()

,animalId,intakeName,intakeDate,intakeMonthYear,foundLocation,intakeReason,intakeCondition,species,sex,age,...,outcomeName,outcomeDate,outcomeMonthYear,outcome,outcomeSubtype,outcomeAnimalType,outcomeSex,outcomeAge,outcomeBreed,outcomeColor
0,A521520,Nina,10/01/2013 07:51:00 AM,October 2013,Norht Ec in Austin (TX),Stray,Normal,dog,Spayed Female,7 years,...,Nina,2013-10-01T15:39:00,10-2013,Return to Owner,NaN,Dog,Spayed Female,7 years,Border Terrier/Border Collie,White/Tan
1,A664235,NaN,10/01/2013 08:33:00 AM,October 2013,Abia in Austin (TX),Stray,Normal,cat,Unknown,1 week,...,NaN,2013-10-01T10:39:00,10-2013,Transfer,Partner,Cat,Unknown,1 week,Domestic Shorthair Mix,Orange/White
2,A664236,NaN,10/01/2013 08:33:00 AM,October 2013,Abia in Austin (TX),Stray,Normal,cat,Unknown,1 week,...,NaN,2013-10-01T10:44:00,10-2013,Transfer,Partner,Cat,Unknown,1 week,Domestic Shorthair Mix,Orange/White
3,A664237,NaN,10/01/2013 08:33:00 AM,October 2013,Abia in Austin (TX),Stray,Normal,cat,Unknown,1 week,...,NaN,2013-10-01T10:44:00,10-2013,Transfer,Partner,Cat,Unknown,1 week,Domestic Shorthair Mix,Orange/White
4,A664233,Stevie,10/01/2013 08:53:00 AM,October 2013,7405 Springtime in Austin (TX),Stray,Injured,dog,Intact Female,3 years,...,Stevie,2013-10-01T15:33:00,10-2013,Euthanasia,Suffering,Dog,Intact Female,3 years,Pit Bull Mix,Blue/White

In [1089]:
# Add Shelter Name, Location and Shelter ID Column

df3['shelterName'] = 'Austin Animal Center'
df3['shelterID'] = 'TXAUAC01'
df3['city'] = 'Austin'
df3['state'] = 'TX'

In [1090]:
# Drop columns not needed for analysis
df3 = df3.drop(columns=["intakeName",
"intakeMonthYear",
"foundLocation",
"intakeCondition",
"age",
"birthdate",
"outcomeName",
"outcomeMonthYear",
"outcomeSubtype",
"outcomeAnimalType",
"outcomeSex",
"outcomeAge",
"outcomeBreed",
"outcomeColor"])

In [1091]:
# Verify column changes

df3.columns

Index(['animalId', 'intakeDate', 'intakeReason', 'species', 'sex', 'breed',
       'color', 'outcomeDate', 'outcome', 'shelterName', 'shelterID', 'city',
       'state'],
      dtype='object')

In [1092]:
# check for missing data
df3.isna()

,animalId,intakeDate,intakeReason,species,sex,breed,color,outcomeDate,outcome,shelterName,shelterID,city,state
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
222105,False,False,False,False,False,False,False,True,True,False,False,False,False
222106,False,False,False,False,False,False,False,True,True,False,False,False,False
222107,False,False,False,False,False,False,False,True,True,False,False,False,False
222108,False,False,False,False,False,False,False,True,True,False,False,False,False
222109,False,False,False,False,False,False,False,True,True,False,False,False,False

In [1093]:
# count of missing data
df3.isna().sum()

animalId          0
intakeDate        0
intakeReason      0
species           0
sex               1
breed             0
color             0
outcomeDate     864
outcome         932
shelterName       0
shelterID         0
city              0
state             0
dtype: int64

In [1094]:
# Fill missing data with simple placeholder text
# This avoids potential issues due to blanks
df3['intakeReason'] = df3['intakeReason'].fillna("unspecified")
df3['breed'] = df3['breed'].fillna("unknown")
df3['outcome'] = df3['outcome'].fillna('unknown')
df3['species'] = df3['species'].fillna('unspecified')
df3['sex'] = df3['sex'].fillna('unknown')
df3['outcomeDate'] = df3['outcomeDate'].fillna(0)

In [1095]:
# count of missing data after filling in some columns
# missing data in outdate and outcome indicates animal remains in shelter
df3.isna().sum()

animalId        0
intakeDate      0
intakeReason    0
species         0
sex             0
breed           0
color           0
outcomeDate     0
outcome         0
shelterName     0
shelterID       0
city            0
state           0
dtype: int64

In [1096]:
# Call the function to convert date columns to datetime to do calculations

df3 = convert_date_columns(df3)

print(df3.indate, df3.outdate)

0        2013-10-01 07:51:00
1        2013-10-01 08:33:00
2        2013-10-01 08:33:00
3        2013-10-01 08:33:00
4        2013-10-01 08:53:00
                 ...
222105   2025-05-03 23:18:00
222106   2025-05-04 15:14:00
222107   2025-05-04 19:43:00
222108   2025-05-04 22:55:00
222109   2025-05-04 23:44:00
Name: indate, Length: 222110, dtype: datetime64[ns] 0        2013-10-01 15:39:00
1        2013-10-01 10:39:00
2        2013-10-01 10:44:00
3        2013-10-01 10:44:00
4        2013-10-01 15:33:00
                 ...
222105                   NaT
222106                   NaT
222107                   NaT
222108                   NaT
222109                   NaT
Name: outdate, Length: 222110, dtype: datetime64[ns]

In [1097]:
# This calls the function that trims the dataframes to the time period of 01-01-2017 thru 07-31-2025

df3 = filter_by_date_range(df3)

In [1098]:
#This is adding a 'A' to the beginning of each animalId to avoid duplicates with Louisville who also starts their animalId's with an A
df3['animalId'] = 'A' + df3['animalId'].astype(str)

In [1099]:
# check for duplicates
df3.duplicated(keep = False)

109616    False
109617    False
109618    False
109619    False
109620    False
          ...
222059    False
222062    False
222063    False
222069    False
222103    False
Length: 28496, dtype: bool

In [1100]:
# count of duplicated data
df3.duplicated(keep = False).sum()

np.int64(42)

In [1101]:
# There can be duplicates on Animal Id due to more than one intake event happening.
# I have decided to keep the latest intake event for anaylsis therefore I am sorting by intakeDate and dropping duplicates except the latest.

df3.drop_duplicates(subset='animalId', keep='last', inplace=True)

In [1102]:
# Validate count of duplicated data after drop of duplicate rows 
df3.duplicated(keep = False).sum()

np.int64(0)

In [1103]:
# This calls the function to create the Intake Categories 
df3 = categorize_intake_reason(df3)

print(df3["intakeCategory"].head())

109616                               Stray
109619                               Stray
109620    Owner Surrender - Non-Behavioral
109621    Owner Surrender - Non-Behavioral
109622    Owner Surrender - Non-Behavioral
Name: intakeCategory, dtype: object

In [1104]:
# This calls the function to create the Outcome Categories 
df3 = categorize_outcome(df3)

print(df3["outcomeCategory"].head())

109616    Adoption
109619    Adoption
109620    Transfer
109621    Transfer
109622    Transfer
Name: outcomeCategory, dtype: object

In [1105]:
# This calls the function that calculates the length of stay and adds it to the dataframe

df3 = add_length_of_stay(df3)

In [1106]:
# This is for testing purposes

print(df3["lengthOfStay"].head())
print(df3["lengthOfStay"].dtype)

109616    18
109619     7
109620     0
109621     0
109622     0
Name: lengthOfStay, dtype: Int64
Int64

In [1107]:
# verify final columns
df3.columns

Index(['animalId', 'intakeDate', 'intakeReason', 'species', 'sex', 'breed',
       'color', 'outcomeDate', 'outcome', 'shelterName', 'shelterID', 'city',
       'state', 'indate', 'outdate', 'intakeCategory', 'outcomeCategory',
       'lengthOfStay'],
      dtype='object')

In [1108]:
# verify the number of rows and columns

df3.shape

(24011, 18)

In [1109]:
 #Create a combined csv file for future use

 df3.to_csv("austin_animal_data_combined.csv", index=False)

In [1110]:
# Count number of animals by type and outcome
outcome_table3 = df3.pivot_table(index='species', columns='outcome', aggfunc='size', fill_value=0)

print(outcome_table3)

outcome    Adoption  Died  Disposal  Euthanasia  Lost  Missing  Relocate  \
species
bird             70     7         3          20     1        0         0
cat            7513   182        61         322     0       11         1
dog            6363    76        33         240     1        3         2
livestock         5     0         0           0     0        0         0
other           218    20        96         711     0        1         0

outcome    Return to Owner  Rto-Adopt  Stolen  Transfer  unknown
species
bird                    10          0       0        23        1
cat                    353         39       0      3783        5
dog                   1390        181       2      2137       11
livestock                1          0       0         2        0
other                    6          0       0       106        1

## Connect and Setup for the SQLite database

In [1111]:
# Connect to the SQLite database (creates if it doesn't exist)

conn = sqlite3.connect('../data/animalshelterdata.db')
cursor = conn.cursor()

# Enable FK constraints
cursor.execute("PRAGMA foreign_keys = ON;")

## Create SQL Lite tables
- Animal
- Shelter
- Intake
- Outcome
- Species

In [1112]:
# Create the Animal table
create_table_sql = """
CREATE TABLE IF NOT EXISTS Animal (
    animalID TEXT PRIMARY KEY,
    species TEXT,
    breed TEXT,
    color TEXT,
    sex TEXT,
    lengthOfStay INTEGER,
    shelterID TEXT
);
"""

cursor.execute(create_table_sql)
conn.commit()

In [1113]:
# Create the Shelter table
create_table_sql = """
CREATE TABLE IF NOT EXISTS Shelter (
    shelterID TEXT PRIMARY KEY,
    name TEXT,
    city TEXT,
    state TEXT
);
"""

cursor.execute(create_table_sql)
conn.commit()

In [1114]:
# Create the Intake table
create_table_sql = """
CREATE TABLE IF NOT EXISTS Intake (
    intakeID INTEGER PRIMARY KEY AUTOINCREMENT,
    intakeDate DATE,
    intakeReason TEXT,
    intakeCategory TEXT,
    indate DATE,
    animalID TEXT,
    shelterID TEXT,

    FOREIGN KEY (animalID) REFERENCES Animal(animalID),
    FOREIGN KEY (shelterID) REFERENCES Shelter(shelterID)
);
"""

cursor.execute(create_table_sql)
conn.commit()

In [1115]:
# Create the Outcome table
create_table_sql = """
CREATE TABLE IF NOT EXISTS Outcome (
    outcomeID INTEGER PRIMARY KEY AUTOINCREMENT,
    outcomeDate DATE,
    outcome TEXT,
    outcomeCategory,
    outdate DATE,
    animalID TEXT,
    shelterID TEXT,

    FOREIGN KEY (animalID) REFERENCES Animal(animalID),
    FOREIGN KEY (shelterID) REFERENCES Shelter(shelterID)
);
"""

cursor.execute(create_table_sql)
conn.commit()

In [1116]:
# Verify the tables exist
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('Animal',), ('Shelter',), ('Intake',), ('sqlite_sequence',), ('Outcome',)]

## Load the Shelter Table with shelter data

In [1117]:
rows = [
    ("KYLMAS01", "Louisville Metro Animal Services", "Louisville", "KY"),
    ("INBLAS01", "Bloomington Animal Services", "Bloomington", "IN"),
    ("TXAUAC01", "Austin Animal Center", "Austin", "TX")
]

cursor.executemany("""
    INSERT OR IGNORE INTO Shelter (shelterID, name, city, state)
    VALUES (?, ?, ?, ?)
""", rows)

conn.commit()

In [1118]:
# Verify the Shelter Load

cursor.execute("""
        SELECT *
        FROM Shelter
        ORDER BY shelterID;
    """)

results = cursor.fetchall()
for row in results:
  print(row)

('INBLAS01', 'Bloomington Animal Services', 'Bloomington', 'IN')
('KYLMAS01', 'Louisville Metro Animal Services', 'Louisville', 'KY')
('TXAUAC01', 'Austin Animal Center', 'Austin', 'TX')

## Load the Animal, Intake and Outcome Tables from the dataframes

In [1119]:
# This creates a dictionary that maps the specific columns of data in the Dataframes to the Tables they need to be loaded into

column_map = {
    "Animal":  ["animalId", "breed", "color", "sex", "species", "lengthOfStay", "shelterID"],
    "Intake":  ["intakeDate", "intakeReason", "intakeCategory", "indate", "animalId", "shelterID"],
    "Outcome": ["outcomeDate", "outcome", "outcomeCategory", "outdate", "animalId", "shelterID"]
}

# This function loads the tables one at a time using the defined dictionary

In [1120]:
# This function loads the tables one at a time using the defined dictionary

def load_dataframe_to_tables(df, conn, column_map):
    for table, cols in column_map.items():
        # Select only the columns needed for this table
        sub_df = df.reindex(columns=cols)
        
        # Insert into SQLite
        sub_df.to_sql(table, conn, if_exists="append", index=False)
        print(f"Loaded {len(sub_df)} rows into {table}")

In [1121]:
# Call the Load Table function for Louisville Dataframe - df

load_dataframe_to_tables(df, conn, column_map)
conn.commit()

Loaded 21130 rows into Animal
Loaded 21130 rows into Intake
Loaded 21130 rows into Outcome

In [1122]:
# Call the Load Table function for Bloomington Dataframe - df2

load_dataframe_to_tables(df2, conn, column_map)
conn.commit()

Loaded 6386 rows into Animal
Loaded 6386 rows into Intake
Loaded 6386 rows into Outcome

In [1123]:
# Call the Load Table function for Austin Dataframe - df3

load_dataframe_to_tables(df3, conn, column_map)
conn.commit()

Loaded 24011 rows into Animal
Loaded 24011 rows into Intake
Loaded 24011 rows into Outcome

In [1124]:
# Verify the Animal Table Load

cursor.execute("SELECT * FROM Animal LIMIT 5")
rows = cursor.fetchall()

for row in rows:
    print(row)

('A658646', 'dog', 'ALASK MALAMUTE', 'BLACK / WHITE', 'M', 0, 'KYLMAS01')
('A602846', 'dog', 'PIT BULL', 'BLACK / WHITE', 'N', 61, 'KYLMAS01')
('A603557', 'cat', 'DOMESTIC SH', 'BUFF', 'N', 13, 'KYLMAS01')
('A596861', 'dog', 'BOXER / MIX', 'WHITE / TAN', 'N', 2, 'KYLMAS01')
('A630199', 'cat', 'DOMESTIC SH', 'BRN TABBY / WHITE', 'S', 12, 'KYLMAS01')

In [1125]:
# Verify the Intake Load

cursor.execute("SELECT * FROM Intake LIMIT 5")
rows = cursor.fetchall()

for row in rows:
    print(row)

(1, '2024-02-05 00:00:00', 'STRAY', 'Stray', '2024-02-05 00:00:00', 'A658646', 'KYLMAS01')
(2, '2024-01-04 00:00:00', 'CONFISCATE', 'Legal Confiscation', '2024-01-04 00:00:00', 'A602846', 'KYLMAS01')
(3, '2024-07-27 00:00:00', 'STRAY', 'Stray', '2024-07-27 00:00:00', 'A603557', 'KYLMAS01')
(4, '2025-04-24 00:00:00', 'STRAY', 'Stray', '2025-04-24 00:00:00', 'A596861', 'KYLMAS01')
(5, '2024-09-24 00:00:00', 'OWNER SUR', 'Owner Surrender - Non-Behavioral', '2024-09-24 00:00:00', 'A630199', 'KYLMAS01')

In [1126]:
# Verify the Outcome Load

cursor.execute("SELECT * FROM Outcome LIMIT 5")
rows = cursor.fetchall()

for row in rows:
    print(row)

(1, '2024-02-05 00:00:00', 'RTO', 'Return to Owner', '2024-02-05 00:00:00', 'A658646', 'KYLMAS01')
(2, '2024-03-05 00:00:00', 'ADOPTION', 'Adoption', '2024-03-05 00:00:00', 'A602846', 'KYLMAS01')
(3, '2024-08-09 00:00:00', 'RTO', 'Return to Owner', '2024-08-09 00:00:00', 'A603557', 'KYLMAS01')
(4, '2025-04-26 00:00:00', 'RTO', 'Return to Owner', '2025-04-26 00:00:00', 'A596861', 'KYLMAS01')
(5, '2024-10-06 00:00:00', 'ADOPTION', 'Adoption', '2024-10-06 00:00:00', 'A630199', 'KYLMAS01')

## Queries against the SQL Lite tables

- First and Second attempts resulted in having to go back and write functions to normalize the data in the cleanup step.  
- SQL Lite has some limitations that PLSQL (which I am used to using) does not have - so Google, StackOverflow and AI was consulted to get around them.

In [ ]:
# query to get the most common outcome by animal species
cursor.execute("""
SELECT 
    a.species,
    i.intakeCategory,
    COUNT(*) AS count_records
FROM Animal AS a
JOIN Intake AS i
    ON a.animalID = i.animalID
GROUP BY a.species, i.intakeCategory
HAVING COUNT(*) = (
    SELECT MAX(cnt)
    FROM (
        SELECT COUNT(*) AS cnt
        FROM Animal AS a2
        JOIN Intake AS i2
            ON a2.animalID = i2.animalID
        WHERE a2.species = a.species
        GROUP BY i2.intakeCategory
    )
)
ORDER BY a.species;            
""")

rows = cursor.fetchall()

for row in rows:
    print(row)

('bird', 'Stray', 109)
('cat', 'Stray', 20962)
('chinchilla', 'Owner Surrender - Non-Behavioral', 2)
('dog', 'Stray', 15075)
('fish', 'Abandoned Neglect', 5)
('gerbil', 'Abandoned Neglect', 2)
('guinea pig', 'Owner Surrender - Non-Behavioral', 21)
('hamster', 'Owner Surrender - Non-Behavioral', 2)
('horse', 'Legal Confiscation', 2)
('house rabbit', 'Stray', 26)
('livestock', 'Stray', 29)
('lizard', 'Abandoned Neglect', 4)
('lizard', 'Stray', 4)
('mouse', 'Abandoned Neglect', 18)
('other', 'Wildlife', 816)
('pig', 'Stray', 2)
('primate', 'Legal Confiscation', 1)
('rabbit', 'Stray', 77)
('skunk', 'Abandoned Neglect', 1)
('snake', 'Abandoned Neglect', 4)
('squirrel', 'Abandoned Neglect', 1)
('turtle', 'Abandoned Neglect', 3)
('wildlife - other', 'Abandoned Neglect', 2)

In [1135]:
# query to get the average length of stay for each species by shelter
cursor.execute("""
SELECT
    s.name,
    a.species,
    MAX(0, ROUND(AVG(a.lengthOfStay))) AS avg_length_of_stay
FROM Animal AS a
JOIN Outcome AS o
    ON a.animalID = o.animalID
JOIN Shelter AS s
    ON a.shelterID = s.shelterID
GROUP BY s.name, a.species
ORDER BY s.name, a.species;
""")

rows = cursor.fetchall()

for row in rows:
    print(row)

('Austin Animal Center', 'bird', 11.0)
('Austin Animal Center', 'cat', 23.0)
('Austin Animal Center', 'dog', 28.0)
('Austin Animal Center', 'livestock', 23.0)
('Austin Animal Center', 'other', 9.0)
('Bloomington Animal Services', 'bird', 4.0)
('Bloomington Animal Services', 'cat', 42.0)
('Bloomington Animal Services', 'chinchilla', 10.0)
('Bloomington Animal Services', 'dog', 46.0)
('Bloomington Animal Services', 'fish', 5.0)
('Bloomington Animal Services', 'gerbil', 14.0)
('Bloomington Animal Services', 'guinea pig', 37.0)
('Bloomington Animal Services', 'hamster', 6.0)
('Bloomington Animal Services', 'horse', 11.0)
('Bloomington Animal Services', 'house rabbit', 66.0)
('Bloomington Animal Services', 'livestock', 10.0)
('Bloomington Animal Services', 'lizard', 47.0)
('Bloomington Animal Services', 'mouse', 2.0)
('Bloomington Animal Services', 'pig', 2.0)
('Bloomington Animal Services', 'primate', 28.0)
('Bloomington Animal Services', 'skunk', 8.0)
('Bloomington Animal Services', 'snake', 14.0)
('Bloomington Animal Services', 'squirrel', 0)
('Bloomington Animal Services', 'turtle', 5.0)
('Bloomington Animal Services', 'wildlife - other', 4.0)
('Louisville Metro Animal Services', 'bird', 15.0)
('Louisville Metro Animal Services', 'cat', 7.0)
('Louisville Metro Animal Services', 'dog', 12.0)
('Louisville Metro Animal Services', 'guinea pig', 2.0)
('Louisville Metro Animal Services', 'livestock', 97.0)
('Louisville Metro Animal Services', 'other', 4.0)
('Louisville Metro Animal Services', 'rabbit', 8.0)

In [ ]:
# query to get average yearly adoption rates by species for each shelter

In [ ]:
conn.close()